Repository acm-ucr/starlight, pull requests merged in 2024-11, with the labels that each got.

#51 Made profile image larger in user/profile component
  src/components/user/profile/header.tsx
Labels: Ready to Review

#53 fixed metadata color
  src/components/user/profile/header.tsx
Labels: Ready to Review

#69 Changed title and fixed spacing
  src/app/admin/[program]/page.tsx
  src/components/programs/project.tsx
Labels: Ready to Review, Projects

#52 Fix Admin Navigation Links
  src/components/global/navigation/side.tsx
  src/data/admin/navigation.tsx
Labels: Ready to Review

#71 made text black on hover
  src/components/global/navigation/side.tsx
Labels: Layout
