Repository acm-ucr/starlight, pull requests merged in 2024-10, with the labels that each got.

#33 Sarbesh1234/create project card
  src/components/programs/project.tsx
Labels: Ready to Review

#17 Create Tag component
  src/components/global/tag.tsx
Labels: Ready to Review, Forms

#21 Added the email input field
  package-lock.json
  package.json
  src/components/applications/application.tsx
  src/components/global/inputs/input.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
Labels: Ready to Review

#27 made header
  src/app/form/[role]/page.tsx
Labels: Ready to Review

#20 Hackinrish/button
  src/app/form/[role]/page.tsx
  src/components/applications/application.tsx
  src/components/global/button.tsx
  src/components/global/inputs/radio.tsx
  src/components/global/inputs/select.tsx
Labels: Ready to Review

#29 Added profile header
  package-lock.json
  package.json
  public/assets/placeholderpic.webp
  src/app/form/[role]/page.tsx
  src/components/applications/application.tsx
  src/components/global/protected.tsx
  src/components/user/profile/header.tsx
  src/components/user/profile/information.tsx
  src/components/user/profile/profile.tsx
  src/components/user/profile/projects.tsx
  src/data/profile/information.ts
  tailwind.config.ts
Labels: Fix Changes

#31 Added Add project modal
  src/components/programs/add.tsx
Labels: Ready to Review, Projects

#28 shadcn radio
  package-lock.json
  package.json
  src/components/global/inputs/radio.tsx
  src/components/ui/radio-group.tsx
Labels: Ready to Review

#23 Created top NavBar using shadcn
  package-lock.json
  package.json
  public/assets/ACMStarlightLogo.webp
  src/app/form/[role]/page.tsx
  src/app/form/layout.tsx
  src/components/global/navigation/index.tsx
  src/components/ui/navigation-menu.tsx
  src/data/forms/navigation.tsx
  src/data/profile/profile-information.ts
Labels: Ready to Review

#26 Adding Application Cards
  package-lock.json
  package.json
  public/assets/ACMStarlightLogo.webp
  public/mock/placeholderpic.webp
  src/components/global/navigation/index.tsx
  src/components/ui/card.tsx
  src/components/user/applications/apply.tsx
  src/components/user/applications/card.tsx
Labels: Ready to Review
